---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-db-pvc
  namespace: jegan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "standard"   # leave empty to use cluster default; set if needed
